package de.training.docker.blog.repository.model;


import lombok.*;

import javax.persistence.*;

@Entity
@Table(name = "author")
@EqualsAndHashCode
@ToString
@NoArgsConstructor
@Getter
@Setter
public class AuthorEntity {
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    private String name;

    private String surname;

    private String email;

}
