package de.training.docker.blog.repository.model;

import lombok.*;

import javax.persistence.*;

@Entity
@Table(name = "post")
@EqualsAndHashCode
@ToString
@NoArgsConstructor
@Getter
@Setter
public class PostEntity {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;


    private String headline;


    private String content;

    @ManyToOne(cascade = {CascadeType.ALL})
    private AuthorEntity author;

}
